/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all bots
         * @description Retrieve a list of all bots
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of bots */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bot"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new bot
         * @description Create a bot with a specified name
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Bot created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bot"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a bot by ID
         * @description Retrieve a bot by its unique ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique ID of the bot */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved bot details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bot"];
                    };
                };
                /** @description Invalid bot ID format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bot not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "_id": "65123abc456def7890123456",
         *       "name": "CharlieBot",
         *       "tasks": [
         *         "65123def456abc7890123456"
         *       ]
         *     } */
        Bot: {
            /** @description The auto-generated ID of the bot */
            _id?: string;
            /** @description The name of the bot */
            name: string;
            tasks?: string[];
        };
        /** @example {
         *       "_id": "65123def456abc7890123456",
         *       "description": "Process Invoice",
         *       "duration": 1500,
         *       "completed": false,
         *       "completedAt": null
         *     } */
        Task: {
            /** @description The auto-generated ID of the task */
            _id?: string;
            /** @description Description of the task */
            description: string;
            /** @description Time in milliseconds before the task is completed */
            duration: number;
            /** @description Indicates whether the task is completed */
            completed?: boolean;
            /**
             * Format: date-time
             * @description Timestamp of when the task was completed
             */
            completedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
